<?php
/**
 * QUANTUM DEEP DIVES - ENHANCED MEDIA LIBRARY v2.5
 * Features: Sticky Player, Real-time Search, Keyboard Shortcuts, Auto-play Next
 * Author: Mark @ Quantum Minds United
 */

$mediaFiles = [];
$directory = __DIR__;

// Supported formats
$supportedFormats = ['m4a', 'mp4', 'mp3', 'wav', 'ogg', 'webm'];

// Scan directory
$files = scandir($directory);
foreach ($files as $file) {
    $extension = strtolower(pathinfo($file, PATHINFO_EXTENSION));
    if (in_array($extension, $supportedFormats)) {
        // NOTEBOOKLM FIX: Treat MP4 as audio, only WebM is video
        $type = in_array($extension, ['webm']) ? 'video' : 'audio';
        
        $mediaFiles[] = [
            'filename' => $file,
            'extension' => $extension,
            'type' => $type,
            'modified' => filemtime($file),
            'size' => filesize($file)
        ];
    }
}

// Default Sort: Modification date (newest first)
usort($mediaFiles, function($a, $b) {
    return $b['modified'] - $a['modified'];
});

// Helper function to format bytes
function formatBytes($bytes, $precision = 1) { 
    $units = array('B', 'KB', 'MB', 'GB', 'TB'); 
    $bytes = max($bytes, 0); 
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024)); 
    $pow = min($pow, count($units) - 1); 
    $bytes /= pow(1024, $pow);
    return round($bytes, $precision) . ' ' . $units[$pow]; 
}

// Calculate total library size
$totalSize = array_sum(array_column($mediaFiles, 'size'));
$totalSizeFormatted = formatBytes($totalSize);

// Separate Featured (Top 2) from Library
$featuredMedia = array_slice($mediaFiles, 0, 2);
$remainingMedia = array_slice($mediaFiles, 2);

// Sort remaining alphabetically for the main grid
usort($remainingMedia, function($a, $b) {
    return strcmp($a['filename'], $b['filename']);
});

$totalCount = count($mediaFiles);
$latestDate = !empty($mediaFiles) ? date('M j', $mediaFiles[0]['modified']) : 'N/A';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <script defer src="https://analytics.quantummindsunited.com/script.js" data-website-id="2d52b4e3-15e0-4b62-9fa9-87628ae9259a"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>🎧 Quantum Deep Dives - Audio Library</title>
    <meta name="description" content="Deep-dive audio podcasts generated by NotebookLM. Explore consciousness, spirituality, and cosmic wisdom.">
    <style>
        :root {
            /* Core Palette */
            --primary-bg: #0a0f1c;
            --card-bg: rgba(26, 31, 53, 0.75);
            --card-border: rgba(139, 143, 164, 0.2);
            --accent-blue: #4a9eff;
            --accent-glow: rgba(74, 158, 255, 0.5);
            --accent-gold: #ffd700;
            --text-primary: #ffffff;
            --text-secondary: #94a3b8;
            
            /* Gradients */
            --gradient-primary: linear-gradient(135deg, #4a9eff, #0066cc);
            --gradient-gold: linear-gradient(135deg, #ffd700, #ffaa00);
            
            /* Effects */
            --shadow-card: 0 8px 32px rgba(0, 0, 0, 0.3);
            --shadow-glow: 0 0 20px rgba(74, 158, 255, 0.15);
            --border-radius: 12px;
            --transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: var(--primary-bg);
            color: var(--text-primary);
            min-height: 100vh;
            padding-bottom: 140px; /* Space for sticky player */
            overflow-x: hidden;
            line-height: 1.6;
        }

        /* --- Animated Background --- */
        .bg-fx {
            position: fixed; top: 0; left: 0; width: 100%; height: 100%;
            pointer-events: none; z-index: -1;
            background: 
                radial-gradient(circle at 15% 50%, rgba(74, 158, 255, 0.08), transparent 25%),
                radial-gradient(circle at 85% 30%, rgba(74, 158, 255, 0.05), transparent 25%);
        }
        .bg-stars {
            position: fixed; top: 0; left: 0; width: 100%; height: 100%;
            background-image: 
                radial-gradient(1px 1px at 20px 30px, #fff, transparent),
                radial-gradient(1px 1px at 100px 70px, rgba(255,255,255,0.5), transparent),
                radial-gradient(2px 2px at 150px 10px, rgba(74,158,255,0.3), transparent);
            background-size: 550px 550px;
            animation: starsMove 100s linear infinite;
            z-index: -1;
            opacity: 0.6;
        }
        @keyframes starsMove { 
            from { background-position: 0 0; } 
            to { background-position: 0 1000px; } 
        }

        .container { max-width: 1400px; margin: 0 auto; padding: 20px; }

        /* --- Header --- */
        .header {
            text-align: center;
            padding: 60px 20px;
            margin-bottom: 40px;
            background: radial-gradient(circle at center, rgba(74, 158, 255, 0.1) 0%, transparent 70%);
            border-bottom: 1px solid var(--card-border);
        }
        .header h1 {
            font-size: clamp(2rem, 5vw, 3rem);
            font-weight: 800;
            background: var(--gradient-primary);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            margin-bottom: 15px;
            letter-spacing: -1px;
        }
        .header .subtitle { 
            color: var(--text-secondary); 
            font-size: clamp(0.9rem, 2vw, 1.1rem);
            margin-bottom: 10px;
        }
        .header a { 
            color: var(--accent-blue); 
            text-decoration: none; 
            border-bottom: 1px dashed var(--accent-blue);
            transition: var(--transition);
        }
        .header a:hover {
            color: white;
            text-shadow: 0 0 10px var(--accent-glow);
        }

        /* --- Controls Bar & Search --- */
        .controls-bar {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-between;
            align-items: center;
            background: var(--card-bg);
            border: 1px solid var(--card-border);
            padding: 20px;
            border-radius: var(--border-radius);
            margin-bottom: 40px;
            backdrop-filter: blur(10px);
            position: sticky;
            top: 20px;
            z-index: 100;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }

        .search-box {
            flex-grow: 1;
            position: relative;
            max-width: 400px;
            min-width: 250px;
        }
        .search-input {
            width: 100%;
            padding: 12px 15px 12px 45px;
            background: rgba(0,0,0,0.2);
            border: 1px solid var(--card-border);
            border-radius: 8px;
            color: white;
            font-size: 1rem;
            transition: var(--transition);
        }
        .search-input:focus {
            outline: none;
            border-color: var(--accent-blue);
            box-shadow: 0 0 0 3px rgba(74, 158, 255, 0.1);
        }
        .search-input::placeholder {
            color: rgba(255, 255, 255, 0.4);
        }
        .search-icon {
            position: absolute;
            left: 15px;
            top: 50%;
            transform: translateY(-50%);
            opacity: 0.5;
        }

        .stats-badge {
            display: flex; 
            gap: 15px;
            font-size: 0.9rem;
            color: var(--text-secondary);
            flex-wrap: wrap;
        }
        .stat-pill {
            background: rgba(255,255,255,0.05);
            padding: 6px 12px;
            border-radius: 20px;
            border: 1px solid rgba(255,255,255,0.1);
            white-space: nowrap;
        }

        .action-cluster {
            display: flex;
            gap: 10px;
            flex-wrap: wrap;
        }
        .ctrl-btn {
            padding: 10px 20px;
            background: rgba(74, 158, 255, 0.1);
            border: 1px solid rgba(74, 158, 255, 0.3);
            color: var(--accent-blue);
            border-radius: 8px;
            cursor: pointer;
            font-weight: 600;
            font-size: 0.9rem;
            transition: var(--transition);
            white-space: nowrap;
        }
        .ctrl-btn:hover {
            background: var(--accent-blue);
            color: white;
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(74, 158, 255, 0.3);
        }

        /* --- Grid Layouts --- */
        .section-title {
            display: flex; 
            align-items: center; 
            gap: 10px;
            font-size: 1.5rem; 
            margin-bottom: 25px;
            color: var(--text-primary);
            font-weight: 700;
        }
        
        .featured-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(min(500px, 100%), 1fr));
            gap: 25px;
            margin-bottom: 50px;
        }

        .media-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(min(350px, 100%), 1fr));
            gap: 20px;
        }

        /* --- Cards --- */
        .media-card {
            background: var(--card-bg);
            border: 1px solid var(--card-border);
            border-radius: var(--border-radius);
            overflow: hidden;
            transition: var(--transition);
            position: relative;
            display: flex;
            flex-direction: column;
            backdrop-filter: blur(10px);
        }
        
        .media-card:hover {
            transform: translateY(-5px);
            border-color: rgba(74, 158, 255, 0.4);
            box-shadow: var(--shadow-glow);
        }

        /* Active Playing State */
        .media-card.active-track {
            border-color: var(--accent-blue);
            background: rgba(74, 158, 255, 0.08);
            box-shadow: 0 0 30px rgba(74, 158, 255, 0.2);
        }
        .media-card.active-track::before {
            content: '';
            position: absolute;
            top: 0; left: 0;
            width: 4px;
            height: 100%;
            background: var(--gradient-primary);
            animation: pulse 2s infinite;
        }
        @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.5; }
        }

        /* Featured Specifics */
        .featured-card {
            border: 1px solid rgba(255, 215, 0, 0.3);
            background: linear-gradient(145deg, rgba(255, 215, 0, 0.05), rgba(26, 31, 53, 0.9));
        }
        .featured-card .badge {
            position: absolute; 
            top: 15px; 
            right: 15px;
            background: var(--gradient-gold);
            color: #000;
            font-weight: bold;
            font-size: 0.75rem;
            padding: 4px 10px;
            border-radius: 4px;
            z-index: 2;
            box-shadow: 0 2px 10px rgba(255, 215, 0, 0.4);
        }

        .card-body { 
            padding: 20px; 
            display: flex; 
            flex-direction: column; 
            height: 100%; 
        }
        
        .card-header {
            display: flex;
            align-items: flex-start;
            gap: 15px;
            margin-bottom: 15px;
        }
        
        .play-btn-large {
            width: 50px; 
            height: 50px;
            border-radius: 50%;
            background: var(--gradient-primary);
            border: none;
            color: white;
            font-size: 1.2rem;
            cursor: pointer;
            flex-shrink: 0;
            display: grid;
            place-items: center;
            box-shadow: 0 4px 15px rgba(74, 158, 255, 0.4);
            transition: var(--transition);
        }
        .play-btn-large:hover { 
            transform: scale(1.1); 
            box-shadow: 0 6px 20px rgba(74, 158, 255, 0.6);
        }
        .play-btn-large:active {
            transform: scale(0.95);
        }
        
        .track-info h3 {
            font-size: 1.1rem;
            line-height: 1.4;
            margin-bottom: 5px;
            word-break: break-word;
            font-weight: 600;
        }
        
        .meta-row {
            display: flex; 
            gap: 15px;
            font-size: 0.85rem;
            color: var(--text-secondary);
            margin-top: auto;
            padding-top: 15px;
            border-top: 1px solid rgba(255,255,255,0.05);
            flex-wrap: wrap;
        }

        .action-row {
            display: flex; 
            gap: 10px; 
            margin-top: 15px;
        }
        .btn-small {
            flex: 1;
            padding: 8px;
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            color: var(--text-secondary);
            border-radius: 6px;
            font-size: 0.85rem;
            cursor: pointer;
            transition: var(--transition);
            text-align: center;
            white-space: nowrap;
        }
        .btn-small:hover {
            background: rgba(255,255,255,0.1);
            color: white;
            border-color: rgba(255,255,255,0.2);
        }

        /* --- Sticky Player --- */
        .sticky-player {
            position: fixed;
            bottom: 0; left: 0; right: 0;
            background: rgba(15, 23, 42, 0.95);
            border-top: 1px solid var(--accent-blue);
            backdrop-filter: blur(15px);
            padding: 15px 20px;
            z-index: 1000;
            transform: translateY(120%);
            transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1);
            box-shadow: 0 -10px 40px rgba(0,0,0,0.5);
        }
        .sticky-player.visible { transform: translateY(0); }

        .player-content {
            max-width: 1200px; 
            margin: 0 auto;
            display: flex; 
            align-items: center; 
            gap: 20px;
        }

        .player-info {
            width: 250px;
            white-space: nowrap;
            overflow: hidden;
        }
        .player-title {
            font-weight: bold;
            color: white;
            display: block;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .player-status { 
            font-size: 0.8rem; 
            color: var(--accent-blue); 
        }

        .player-controls-wrapper {
            flex-grow: 1;
            display: flex; 
            flex-direction: column; 
            gap: 5px;
        }

        /* Custom Audio Player Styling */
        audio { 
            width: 100%; 
            height: 35px; 
            border-radius: 5px;
            outline: none;
        }
        
        .close-player {
            background: none; 
            border: none; 
            color: var(--text-secondary);
            cursor: pointer; 
            font-size: 1.5rem; 
            padding: 0 10px;
            transition: var(--transition);
        }
        .close-player:hover {
            color: white;
            transform: scale(1.1);
        }

        /* --- Utilities --- */
        .hidden { display: none !important; }
        
        .toast {
            position: fixed; 
            top: 20px; 
            right: 20px;
            background: linear-gradient(135deg, #10b981, #059669);
            color: white;
            padding: 12px 24px; 
            border-radius: 8px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
            transform: translateX(150%); 
            transition: transform 0.3s;
            z-index: 2000;
            font-weight: 600;
        }
        .toast.show { transform: translateX(0); }

        .empty-state {
            text-align: center;
            padding: 80px 20px;
            background: var(--card-bg);
            border: 1px solid var(--card-border);
            border-radius: var(--border-radius);
            backdrop-filter: blur(10px);
        }
        .empty-state h3 {
            font-size: 1.5rem;
            margin-bottom: 15px;
            color: var(--accent-blue);
        }
        .empty-state p {
            color: var(--text-secondary);
            margin-bottom: 10px;
        }
        .empty-state code {
            background: rgba(0,0,0,0.3);
            padding: 2px 8px;
            border-radius: 4px;
            color: var(--accent-blue);
        }

        /* Mobile Responsive */
        @media (max-width: 768px) {
            body { padding-bottom: 200px; }
            .header { padding: 40px 20px; }
            .controls-bar { 
                flex-direction: column; 
                align-items: stretch;
                position: relative;
                top: 0;
            }
            .search-box { 
                max-width: 100%; 
                min-width: 100%;
            }
            .stats-badge {
                justify-content: center;
            }
            .action-cluster {
                width: 100%;
            }
            .ctrl-btn {
                flex: 1;
            }
            .player-content { 
                flex-direction: column; 
                align-items: stretch; 
                gap: 10px; 
            }
            .player-info { 
                width: 100%; 
                text-align: center; 
            }
            .featured-grid, .media-grid { 
                grid-template-columns: 1fr; 
            }
        }
    </style>
</head>
<body>

<div class="bg-fx"></div>
<div class="bg-stars"></div>

<div class="container">
    
    <header class="header">
        <h1>🎧 The Quantum Library</h1>
        <p class="subtitle">Deep-Dive Audio Collection generated by <a href="https://notebooklm.google.com/" target="_blank">NotebookLM</a></p>
        <p class="subtitle" style="font-size: 0.85rem; opacity: 0.7; margin-top: 5px;">
            Listen • Share • Download • Explore
        </p>
    </header>

    <?php if (empty($mediaFiles)): ?>
        <div class="empty-state">
            <h3>📂 No Audio Files Found</h3>
            <p>Upload MP3, MP4, M4A, or WAV files to get started.</p>
            <p style="margin-top: 15px;"><strong>Directory:</strong> <code><?php echo htmlspecialchars($directory); ?></code></p>
            <p style="margin-top: 10px; font-size: 0.85rem; color: var(--text-secondary);">
                Supported formats: MP3, MP4, M4A, WAV, OGG, WebM
            </p>
        </div>
    <?php else: ?>

        <div class="controls-bar">
            <div class="search-box">
                <span class="search-icon">🔍</span>
                <input 
                    type="text" 
                    id="searchInput" 
                    class="search-input" 
                    placeholder="Filter by title..."
                    autocomplete="off"
                    spellcheck="false"
                >
            </div>
            
            <div class="stats-badge">
                <div class="stat-pill" id="trackCountPill">💿 <?php echo $totalCount; ?> Tracks</div>
                <div class="stat-pill" id="latestDatePill">📅 Latest: <?php echo $latestDate; ?></div>
                <div class="stat-pill">💾 <?php echo $totalSizeFormatted; ?></div>
            </div>

            <div class="action-cluster">
                <button class="ctrl-btn" onclick="playAll()">▶️ Play All</button>
                <button class="ctrl-btn" onclick="shufflePlay()">🔀 Shuffle</button>
            </div>
        </div>

        <?php if (!empty($featuredMedia)): ?>
        <div class="section-title">✨ New Releases</div>
        <div class="featured-grid">
            <?php foreach ($featuredMedia as $index => $file): 
                $cleanName = ucwords(str_replace(['_', '-'], ' ', pathinfo($file['filename'], PATHINFO_FILENAME)));
                $dataTitle = htmlspecialchars($cleanName);
                $dataFile = htmlspecialchars($file['filename']);
            ?>
            <div class="media-card featured-card track-item" 
                 data-title="<?php echo $dataTitle; ?>"
                 data-filename="<?php echo $dataFile; ?>"
                 data-modified="<?php echo $file['modified']; ?>">
                <div class="badge">NEW RELEASE</div>
                <div class="card-body">
                    <div class="card-header">
                        <button class="play-btn-large" onclick="loadTrack(this)">▶</button>
                        <div class="track-info">
                            <h3><?php echo $cleanName; ?></h3>
                            <div style="font-size: 0.8rem; color: var(--accent-gold);">
                                <?php echo date('F j, Y', $file['modified']); ?>
                            </div>
                        </div>
                    </div>
                    <div class="action-row">
                        <button class="btn-small" onclick="copyLink('<?php echo $dataFile; ?>')">🔗 Copy Link</button>
                        <button class="btn-small" onclick="downloadFile('<?php echo $dataFile; ?>')">⬇ Download</button>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>

        <div class="section-title">📚 Full Collection</div>
        <div class="media-grid" id="libraryGrid">
            <?php foreach ($remainingMedia as $index => $file): 
                $cleanName = ucwords(str_replace(['_', '-'], ' ', pathinfo($file['filename'], PATHINFO_FILENAME)));
                $dataTitle = htmlspecialchars($cleanName);
                $dataFile = htmlspecialchars($file['filename']);
            ?>
            <div class="media-card track-item" 
                 data-title="<?php echo $dataTitle; ?>"
                 data-filename="<?php echo $dataFile; ?>"
                 data-modified="<?php echo $file['modified']; ?>">
                <div class="card-body">
                    <div class="card-header">
                        <button class="play-btn-large" onclick="loadTrack(this)">▶</button>
                        <div class="track-info">
                            <h3><?php echo $cleanName; ?></h3>
                        </div>
                    </div>
                    <div class="meta-row">
                        <span>📄 <?php echo strtoupper($file['extension']); ?></span>
                        <span>💾 <?php echo formatBytes($file['size']); ?></span>
                        <span>📅 <?php echo date('M j', $file['modified']); ?></span>
                    </div>
                    <div class="action-row">
                        <button class="btn-small" onclick="copyLink('<?php echo $dataFile; ?>')">🔗 Link</button>
                        <button class="btn-small" onclick="downloadFile('<?php echo $dataFile; ?>')">⬇ Down</button>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

    <?php endif; ?>
</div>

<div id="stickyPlayer" class="sticky-player">
    <div class="player-content">
        <div class="player-info">
            <div id="playerTitle" class="player-title">Select a track...</div>
            <div id="playerStatus" class="player-status">Ready to play</div>
        </div>
        
        <div class="player-controls-wrapper">
            <audio id="globalAudio" controls controlsList="nodownload" preload="metadata">
                <source src="" type="audio/mp4">
                Your browser does not support audio playback.
            </audio>
        </div>
        
        <button class="close-player" onclick="closePlayer()" title="Close Player (Esc)">✕</button>
    </div>
</div>

<div id="toast" class="toast">✅ Action Complete</div>

<script>
    // ==========================================
    // GLOBAL STATE
    // ==========================================
    const audioPlayer = document.getElementById('globalAudio');
    const playerTitle = document.getElementById('playerTitle');
    const playerStatus = document.getElementById('playerStatus');
    const stickyPlayer = document.getElementById('stickyPlayer');
    const searchInput = document.getElementById('searchInput');
    const trackCountPill = document.getElementById('trackCountPill');
    const latestDatePill = document.getElementById('latestDatePill');
    
    let currentButton = null;
    let currentCard = null;
    
    const TOTAL_TRACKS = <?php echo $totalCount; ?>;
    
    // ==========================================
    // PLAYER LOGIC
    // ==========================================
    function loadTrack(btn) {
        const card = btn.closest('.track-item');
        const filename = card.dataset.filename;
        const title = card.dataset.title;

        // Visual Update
        document.querySelectorAll('.media-card').forEach(c => c.classList.remove('active-track'));
        document.querySelectorAll('.play-btn-large').forEach(b => b.textContent = '▶');
        
        card.classList.add('active-track');
        btn.textContent = '⏳'; // Loading state
        currentButton = btn;
        currentCard = card;

        // Player Update
        playerTitle.textContent = title;
        playerStatus.textContent = "Loading...";
        
        // Audio Load (browser handles encoding automatically)
        audioPlayer.src = filename;
        
        // Wait for canplay event before starting
        audioPlayer.addEventListener('canplay', function handleCanPlay() {
            audioPlayer.removeEventListener('canplay', handleCanPlay);
            btn.textContent = '⏸';
            playerStatus.textContent = "Playing...";
            
            audioPlayer.play().catch(e => {
                console.error("Playback prevented:", e);
                btn.textContent = '▶';
                playerStatus.textContent = "Ready";
                showToast("⚠️ Playback blocked. Click play again.");
            });
        });
        
        // Show Sticky Player
        stickyPlayer.classList.add('visible');

        // Smooth scroll to playing card
        setTimeout(() => {
            card.scrollIntoView({ 
                behavior: 'smooth', 
                block: 'center',
                inline: 'nearest'
            });
        }, 200);
    }

    // Toggle play/pause if clicking same button
    document.addEventListener('click', function(e) {
        if(e.target.classList.contains('play-btn-large') && e.target === currentButton) {
            if(audioPlayer.paused) {
                audioPlayer.play();
                e.target.textContent = '⏸';
                playerStatus.textContent = "Playing...";
            } else {
                audioPlayer.pause();
                e.target.textContent = '▶';
                playerStatus.textContent = "Paused";
            }
        }
    });

    // ==========================================
    // AUDIO EVENT LISTENERS
    // ==========================================
    audioPlayer.addEventListener('ended', () => {
        playNextTrack();
    });

    audioPlayer.addEventListener('pause', () => {
        if(currentButton) currentButton.textContent = '▶';
        playerStatus.textContent = "Paused";
    });

    audioPlayer.addEventListener('play', () => {
        if(currentButton) currentButton.textContent = '⏸';
        playerStatus.textContent = "Playing...";
    });

    audioPlayer.addEventListener('error', (e) => {
        console.error("Audio error:", e);
        if(currentButton) currentButton.textContent = '▶';
        playerStatus.textContent = "Error loading audio";
        showToast("❌ Failed to load audio");
    });

    // ==========================================
    // PLAYLIST NAVIGATION
    // ==========================================
    function getVisibleCards() {
        return Array.from(document.querySelectorAll('.track-item'))
            .filter(card => card.style.display !== 'none');
    }

    function playNextTrack() {
        const visibleCards = getVisibleCards();
        let currentIndex = visibleCards.indexOf(currentCard);
        
        if (currentIndex !== -1 && currentIndex < visibleCards.length - 1) {
            const nextBtn = visibleCards[currentIndex + 1].querySelector('.play-btn-large');
            loadTrack(nextBtn);
        } else {
            // End of playlist
            playerStatus.textContent = "Playlist finished";
            if(currentButton) currentButton.textContent = '▶';
        }
    }

    function playPrevTrack() {
        const visibleCards = getVisibleCards();
        let currentIndex = visibleCards.indexOf(currentCard);
        
        if (currentIndex > 0) {
            const prevBtn = visibleCards[currentIndex - 1].querySelector('.play-btn-large');
            loadTrack(prevBtn);
        }
    }

    function playAll() {
        const firstCard = getVisibleCards()[0];
        if(firstCard) {
            const btn = firstCard.querySelector('.play-btn-large');
            loadTrack(btn);
        }
    }

    function shufflePlay() {
        const visibleCards = getVisibleCards();
        if(visibleCards.length === 0) return;
        
        const randomCard = visibleCards[Math.floor(Math.random() * visibleCards.length)];
        const btn = randomCard.querySelector('.play-btn-large');
        loadTrack(btn);
        
        showToast("🔀 Shuffled!");
    }

    // ==========================================
    // SEARCH FUNCTIONALITY
    // ==========================================
    searchInput.addEventListener('input', (e) => {
        const term = e.target.value.toLowerCase().trim();
        const cards = document.querySelectorAll('.track-item');
        let visibleCount = 0;
        let latestTimestamp = 0;

        cards.forEach(card => {
            const title = card.dataset.title.toLowerCase();
            if(title.includes(term)) {
                card.style.display = 'flex';
                visibleCount++;
                
                // Track latest visible file
                const modified = parseInt(card.dataset.modified);
                if(modified > latestTimestamp) {
                    latestTimestamp = modified;
                }
            } else {
                card.style.display = 'none';
            }
        });
        
        // Update stats dynamically
        trackCountPill.textContent = `💿 ${visibleCount} Track${visibleCount !== 1 ? 's' : ''}`;
        
        if(latestTimestamp > 0) {
            const latestDate = new Date(latestTimestamp * 1000);
            const formatted = latestDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
            latestDatePill.textContent = `📅 Latest: ${formatted}`;
        }
    });

    // Clear search on Escape
    searchInput.addEventListener('keydown', (e) => {
        if(e.key === 'Escape') {
            searchInput.value = '';
            searchInput.dispatchEvent(new Event('input'));
            searchInput.blur();
        }
    });

    // ==========================================
    // KEYBOARD SHORTCUTS
    // ==========================================
    document.addEventListener('keydown', (e) => {
        // Ignore if typing in search
        if(e.target === searchInput) return;
        
        // Space: Play/Pause
        if(e.code === 'Space') {
            e.preventDefault();
            if(currentButton) {
                currentButton.click();
            }
        }
        
        // Ctrl/Cmd + Right Arrow: Next Track
        if(e.code === 'ArrowRight' && (e.ctrlKey || e.metaKey)) {
            e.preventDefault();
            playNextTrack();
        }
        
        // Ctrl/Cmd + Left Arrow: Previous Track
        if(e.code === 'ArrowLeft' && (e.ctrlKey || e.metaKey)) {
            e.preventDefault();
            playPrevTrack();
        }
        
        // Escape: Close Player
        if(e.code === 'Escape') {
            closePlayer();
        }
        
        // S: Focus Search
        if(e.code === 'KeyS' && !e.ctrlKey && !e.metaKey) {
            e.preventDefault();
            searchInput.focus();
        }
    });

    // ==========================================
    // UTILITIES
    // ==========================================
    function closePlayer() {
        stickyPlayer.classList.remove('visible');
        audioPlayer.pause();
        if(currentButton) currentButton.textContent = '▶';
        if(currentCard) currentCard.classList.remove('active-track');
        playerTitle.textContent = "Select a track...";
        playerStatus.textContent = "Ready to play";
    }

    function copyLink(filename) {
        const baseUrl = window.location.origin + window.location.pathname.replace('index.php', '');
        const url = baseUrl + encodeURIComponent(filename);
        
        navigator.clipboard.writeText(url)
            .then(() => showToast("✅ Link copied to clipboard!"))
            .catch(err => {
                console.error('Copy failed:', err);
                showToast("❌ Failed to copy link");
            });
    }

    function downloadFile(filename) {
        const a = document.createElement('a');
        a.href = filename;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        
        showToast("⬇️ Download started!");
    }

    function showToast(msg) {
        const toast = document.getElementById('toast');
        toast.textContent = msg;
        toast.classList.add('show');
        setTimeout(() => toast.classList.remove('show'), 3000);
    }

    // ==========================================
    // INITIALIZATION
    // ==========================================
    console.log('🎧 Quantum Deep Dives Library Loaded');
    console.log(`📊 Total Tracks: ${TOTAL_TRACKS}`);
    console.log('⌨️  Keyboard Shortcuts:');
    console.log('   Space: Play/Pause');
    console.log('   Ctrl+→: Next Track');
    console.log('   Ctrl+←: Previous Track');
    console.log('   S: Focus Search');
    console.log('   Esc: Close Player');
</script>

</body>
</html>
